image: node:12

before_script:
  - npm install -g liyad-cli

#cache:
#  paths:
#    - node_modules/

test:node:12:
  script:
    - liyad index.lisp

test:node:11:
  image: node:11
  script:
    - liyad index.lisp

# LTS
test:node:10:
  image: node:10
  script:
    - liyad index.lisp
